name: Build

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-android-web:
    name: Android & Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build Android
        run: ./gradlew androidApp:assembleDebug

      - name: Build JS
        run: ./gradlew composeApp:jsBrowserProductionWebpack

      - name: Build Wasm
        run: ./gradlew composeApp:wasmJsBrowserProductionWebpack
